create table if not exists public.vendas (
  id bigint generated by default as identity primary key,
  data date not null,
  cliente text not null,
  valor numeric(12, 2) not null check (valor > 0),
  pagamento text not null default 'PIX',
  obs text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.fornecedores (
  id bigint generated by default as identity primary key,
  nome text not null,
  tel text not null default '',
  email text not null default '',
  produtos text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.contas (
  id bigint generated by default as identity primary key,
  "desc" text not null,
  valor numeric(12, 2) not null check (valor > 0),
  venc date,
  status text not null default 'Pendente' check (status in ('Pendente', 'Pago')),
  created_at timestamptz not null default now()
);

alter table public.vendas enable row level security;
alter table public.fornecedores enable row level security;
alter table public.contas enable row level security;
